spring:
  application:
    name: base-web

  profiles:
    active: @profiles.active@
  jackson:
    time-zone: GMT+8
    date-format: 'yyyy-MM-dd HH:mm:ss'

###### mybatis-plus ######
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.base.common.entity
  # 类型转换处理
  # type-handlers-package: com.base.common.config.MybatisPlusLocalDateTimeTypeHandler
  check-config-location: true
  configuration:
    use-generated-keys: true # 使用自增主键
    map-underscore-to-camel-case: true # 开启驼峰命名转换
    cache-enabled: true # 配置的缓存的全局开关
    lazy-loading-enabled: true # 延时加载的开关
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
    auto-mapping-unknown-column-behavior: warning
    multiple-result-sets-enabled: true # 开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
  global-config:
    banner: false
    db-config:
      # 主键类型  auto:"数据库ID自增" 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ASSIGN_UUID
      capital-mode: true

###### log ######
logging:
  level:
    root: info
    org.springframework.web: error
    com.base: info
  file:
    path: /log/base-boot
  config: classpath:logback-spring.xml


